# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Journal
email: mashonthomas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documenting my experimentation and builds in a variety of languages, libraries and frameworks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mashonthomas
github_username:  mashon
linkedin_username: mashon
# Build settings
markdown: kramdown
